# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Hello.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Hello.proto',
  package='com.protobuf.proto',
  syntax='proto3',
  serialized_options=_b('\n\022com.protobuf.protoB\tHelloInfoP\001'),
  serialized_pb=_b('\n\x0bHello.proto\x12\x12\x63om.protobuf.proto\"\x16\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x06Result\x12\x0e\n\x06string\x18\x01 \x01(\t2\xc8\x02\n\x0cHelloService\x12G\n\x0bsimpleHello\x12\x1a.com.protobuf.proto.Person\x1a\x1a.com.protobuf.proto.Result\"\x00\x12O\n\x11serverStreamHello\x12\x1a.com.protobuf.proto.Person\x1a\x1a.com.protobuf.proto.Result\"\x00\x30\x01\x12O\n\x11\x63lientStreamHello\x12\x1a.com.protobuf.proto.Person\x1a\x1a.com.protobuf.proto.Result\"\x00(\x01\x12M\n\rbiStreamHello\x12\x1a.com.protobuf.proto.Person\x1a\x1a.com.protobuf.proto.Result\"\x00(\x01\x30\x01\x42!\n\x12\x63om.protobuf.protoB\tHelloInfoP\x01\x62\x06proto3')
)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='com.protobuf.proto.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='com.protobuf.proto.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=57,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='com.protobuf.proto.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string', full_name='com.protobuf.proto.Result.string', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:com.protobuf.proto.Person)
  ))
_sym_db.RegisterMessage(Person)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:com.protobuf.proto.Result)
  ))
_sym_db.RegisterMessage(Result)


DESCRIPTOR._options = None

_HELLOSERVICE = _descriptor.ServiceDescriptor(
  name='HelloService',
  full_name='com.protobuf.proto.HelloService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=86,
  serialized_end=414,
  methods=[
  _descriptor.MethodDescriptor(
    name='simpleHello',
    full_name='com.protobuf.proto.HelloService.simpleHello',
    index=0,
    containing_service=None,
    input_type=_PERSON,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='serverStreamHello',
    full_name='com.protobuf.proto.HelloService.serverStreamHello',
    index=1,
    containing_service=None,
    input_type=_PERSON,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='clientStreamHello',
    full_name='com.protobuf.proto.HelloService.clientStreamHello',
    index=2,
    containing_service=None,
    input_type=_PERSON,
    output_type=_RESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='biStreamHello',
    full_name='com.protobuf.proto.HelloService.biStreamHello',
    index=3,
    containing_service=None,
    input_type=_PERSON,
    output_type=_RESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HELLOSERVICE)

DESCRIPTOR.services_by_name['HelloService'] = _HELLOSERVICE

# @@protoc_insertion_point(module_scope)
