// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.protobuf.proto;

public final class HelloInfo {
  private HelloInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_proto_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_proto_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_proto_Result_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_proto_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Hello.proto\022\022com.protobuf.proto\"\026\n\006Per" +
      "son\022\014\n\004name\030\001 \001(\t\"\030\n\006Result\022\016\n\006string\030\001 " +
      "\001(\t2\310\002\n\014HelloService\022G\n\013simpleHello\022\032.co" +
      "m.protobuf.proto.Person\032\032.com.protobuf.p" +
      "roto.Result\"\000\022O\n\021serverStreamHello\022\032.com" +
      ".protobuf.proto.Person\032\032.com.protobuf.pr" +
      "oto.Result\"\0000\001\022O\n\021clientStreamHello\022\032.co" +
      "m.protobuf.proto.Person\032\032.com.protobuf.p" +
      "roto.Result\"\000(\001\022M\n\rbiStreamHello\022\032.com.p" +
      "rotobuf.proto.Person\032\032.com.protobuf.prot" +
      "o.Result\"\000(\0010\001B!\n\022com.protobuf.protoB\tHe" +
      "lloInfoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protobuf_proto_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protobuf_proto_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_proto_Person_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_protobuf_proto_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protobuf_proto_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_proto_Result_descriptor,
        new java.lang.String[] { "String", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
