// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.protobuf.proto;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protobuf.proto.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
