// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package com.protobuf.proto;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protobuf.proto.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string string = 1;</code>
   */
  java.lang.String getString();
  /**
   * <code>string string = 1;</code>
   */
  com.google.protobuf.ByteString
      getStringBytes();
}
